
/**
* Autogenerated code from the Exceptional compiler, https://github.com/rjhunjhunwala/Exceptional
*/
import java.util.Stack;
public class CountDown{
//all code after this point, is done with max effort!
public static void countingOne(){
try{
int c=0;
c=b[a];
System.out.print(a);
System.out.print("\n");
s.push(a);a=a-1;
countingOne();
}
catch(Throwable someLongThrowablesdasdashToNotPolluteNamespaceadsdsasaddassadsda){
//gotta catch em all
}
}
public static void countingTwo(){
try{
int temp=0;
temp=s.pop();
System.out.print(temp);
System.out.print("\n");
countingTwo();
}
catch(Throwable someLongThrowablesdasdashToNotPolluteNamespaceadsdsasaddassadsda){
//gotta catch em all
}
}
public static int a=0;
public static int[] b=new int[65535];
public static Stack<Integer> s=new Stack<>();
public static void main(String...args){
a=10;
countingOne();
countingTwo();
}
}
