import sys
import os
from subprocess import call
def remove_leading_spaces(string):
    if not string:
        return ""
    else:
        return string if string[0]!=" " else remove_leading_spaces(string[1:])
def get_compiled_source(lines):
    source = """
    /**
    * Autogenerated code from the Exceptional compiler
    */
    """
    source += "public class "+ get_class_name()+"{\n"
    source += "public static void main(String...args){\n"
    source += 'System.out.println("Go Bears!!");\n'
    source += "}\n"
    source += "}\n"
    return source

def get_class_name():
    if "." in args[0]:
        return args[0][0:args[0].index(".")]

args = sys.argv[1:]

if not args or len(args)>2 or (len(args)==2 and args[1]!="-c"):
    print("Usage guidelines: (compile and run)")
    print("python3 Exceptional.py filename.exc")
    print("To only compile to a class:")
    print("python3 Exceptional.py filename.exc -c")
    print("To, then run that compiled file, run 'java filename'")
    quit(1)

try:
    file = open(args[0],"r")
    lines = file.readlines()
except:
    print("Invalid file"+args[0])
    quit(1)

compiled = get_compiled_source(lines)

out = open(get_class_name()+".java","w")
out.write(compiled)
out.close()
command = "javac "+get_class_name()+".java"
os.system(command)
os.system
if len(args)==1:
    os.system("java " + get_class_name())

