import sys
import os

def remove_leading_spaces(string):
    if not string:
        return ""
    else:
        return string if string[0]!=" " else remove_leading_spaces(string[1:])

is_giving_it_all = False

def good_code(rest, in_global_scope):
    global is_giving_it_all
    is_giving_it_all = True
    return "//all code after this point, is done with max effort!\n"


def get_compiled_source(lines):
    """
    Creates a java file from the lines in source
    :param lines: the lines from the input file
    :return: a string which represents the java equivalent of the exceptional code
    """
    source ="""
/**
* Autogenerated code from the Exceptional compiler, 
*/
"""
    global is_giving_it_all

    source += "public class "+ get_class_name()+"{\n"

    is_in_func = False
    main_code = []

    dispatch = {"GIVE_IT_110_PERCENT!",(good_code, False), "PROCEDURE", (procedure, True)}

    for line in lines:
        line = remove_leading_spaces(line)

    source += "public static void main(String...args){\n"

    for line in main_code:
        line = line[0]
    source += "}\n"
    source += "}\n"
    return source

def get_class_name():
    if "." in args[0]:
        return args[0][0:args[0].index(".")]

args = sys.argv[1:]

if not args or len(args)>2 or (len(args)==2 and args[1]!="-c"):
    print("Usage guidelines: (compile and run)")
    print("python3 Exceptional.py filename.exc")
    print("To only compile to a class:")
    print("python3 Exceptional.py filename.exc -c")
    print("To, then run that compiled file, run 'java filename'")
    quit(1)

try:
    file = open(args[0],"r")
    lines = file.readlines()
except:
    print("Invalid file"+args[0])
    quit(1)

compiled = get_compiled_source(lines)

out = open(get_class_name()+".java","w")
out.write(compiled)
out.close()
command = "javac "+get_class_name()+".java"

os.system(command)
os.system

if len(args)==1:
    os.system("java " + get_class_name())

