
/**
* Autogenerated code from the Exceptional compiler, https://github.com/rjhunjhunwala/Exceptional
*/
import java.util.Stack;
public class HelloWorld{
//all code after this point, is done with max effort!
public static void main(String...args){
System.out.print("Hello, World!");
}
}
